import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ClientProvider from "@/ClientProvider";

export const metadata: Metadata = {
  title: "My Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          {children}
          <Toaster position="top-right" />
        </ClientProvider>
      </body>
    </html>
  );
}
